model_list:
  - model_name: product-architect
    litellm_params:
      model: nvidia_nim/deepseek-ai/deepseek-v3.2
      api_key: os.environ/NVIDIA_NIM_API_KEY_PRODUCT_ARCHITECT

  - model_name: backend
    litellm_params:
      model: nvidia_nim/mistralai/devstral-2-123b-instruct-2512
      api_key: os.environ/NVIDIA_NIM_API_KEY_BACKEND

  - model_name: ios
    litellm_params:
      model: nvidia_nim/z-ai/glm4.7
      api_key: os.environ/NVIDIA_NIM_API_KEY_IOS

  - model_name: android
    litellm_params:
      model: nvidia_nim/z-ai/glm4.7
      api_key: os.environ/NVIDIA_NIM_API_KEY_ANDROID

  - model_name: qa
    litellm_params:
      model: nvidia_nim/deepseek-ai/deepseek-v3.1-terminus
      api_key: os.environ/NVIDIA_NIM_API_KEY_QA

litellm_settings:
  drop_params: True

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

